### ISSUE TITLE
LG201606P2 - 직각다각형

### ISSUE THREAD

**Issue by congr** [congr/world#4]
직각다각형
N개의 꼭지점으로 이루어진 다각형에서 각 꼭지점의 내각이 90o 또는 270o이며, 어느 두 변도 서 로 교차하지 않으며, 각 꼭지점의 좌표가 서로 다른 다각형을 직각다각형이라 부른다.

![image](https://cloud.githubusercontent.com/assets/9853714/17467431/2c11db66-5d59-11e6-9660-0ffd8c7d7cb7.png)

예를 들어, 그림 (a)에서 보인 것처럼 8개의 꼭지점으로 이루어진 직각다각형을 고려해 보자. 각 변 에 적혀 있는 수는 그 변의 길이를 나타낸다. 이런 직각다각형을 표현하는 방법 중 하나는 임의의 한 꼭지점에서 시작하여 임의의 방향으로 변을 따라 이동하면서 그 변의 길이와, 그 변에서 다음 변으로 가기 위해 어떤 방향으로 회전해야 하는지를 나타내는 회전방향의 정보를 차례로 적는 것이 다. 예를 들어, 그림 (b)에서 보인 것처럼 굵은 화살표의 시작 꼭지점에서 시작하여 화살표 방향으 로 다각형의 변을 다라 차례로 이동하면서 정보를 나열하면 다음과 같다. 여기서 ‘L’은 좌회전(Left turn)을, ‘R’은 우회전(Right turn)을 의미한다.
(2, R), (3, L), (2, L), (2, R), (3, R), (4, R), (7, R), (5, R)
유사하게, 그림 (c)에서 보인 것처럼 시작 꼭지점과 방향이 다르면 다음과 같은 열을 얻을 수 있다.
(4, L), (3, L), (2, R), (2, R), (3, L), (2, L), (5, L), (7, L)
물론 이 두 열은 동일한 직각다각형을 나타내는 서로 다른 표현이다. 변의 길이를 𝑙𝑒𝑛이라고 할 때, (𝑙en, L)은 𝑙𝑒𝑛(양수)으로, (𝑙𝑒𝑛, R)을 –𝑙𝑒𝑛(음수)으로 나타내면 직각다각형에 대한 정보는 N개의 정 수로 구성된 리스트로 표시할 수 있다. 그림 (b)와 그림 (c)에서 보인 것에 대응하는 정수리스트는 각각 다음과 같다.
(-2, 3, 2, -2, -3, -4, -7, -5), (4, 3, -2, -2, 3, 2, 5, 7)
각각 N개의 정수로 구성된 두 정수리스트 𝑆1과 𝑆2가 주어질 때, 그 두 정수 리스트가 동일한 직각 다각형을 표현하는 것인지 아니면 서로 다른 직각다각형을 표현하는 것인지를 밝히는 프로그램을 작성하라.

[입력]
입력 파일의 제일 첫째 줄에는 파일에 포함된 케이스의 수 T가 주어진다. 단, T ≤ 65이다. 각 케이 스는 세 줄로 구성된다. 첫째 줄에는 직각다각형의 꼭지점의 개수를 나타내는 정수 N이 주어진다. 이어서, 다음 줄에는 문제에서 설명한 직각다각형의 정보를 나타내는 N개의 정수로 구성된 리스트 가 주어지며, 다음 줄에는 또 다른 N개의 정수로 구성된 리스트가 주어진다. 정수 리스트에서 주어 지는 모든 정수의 절대값은 1이상 100이하이며, 각 정수리스트는 모두 직각다각형을 표현하는 것 이다.
   입력은 다음의 두 가지 종류로 주어진다.
 Set1:4≤N≤1,000
 Set2:4≤N≤100,000

[출력]
입력에서 주어진 각 테스트 케이스에 대해 하나의 정수 값을 한 줄에 출력한다. 주어진 두 정수 리 스트가 동일한 직각다각형을 위한 표현이면 1, 아니면 0을 출력한다.

![image](https://cloud.githubusercontent.com/assets/9853714/17467444/3e35ea62-5d59-11e6-8507-232596a0d9ab.png)

**Comment by congr** [comment]
문제만 잘 이해하면 어렵지 않은 문제. - KMP 알고리즘을 썼는데,  안써도 시간내 해결가능 하단다.

 ```
	static int solve(int[] aRo, int[] bRo) {
		int[] cRo = new int[N * 2];

		// 방향 반대일 경우, 부호 반대로..
		// 경로가 (-2, 3, 2, -2, -3, -4, -7, -5)였다면 뒤집으면 (5, 7, 4, 3, -2, -2, 3, 2)
		for (int i = N - 1, j = 0; i >= 0; i--, j++) {
			cRo[j] = Math.abs(aRo[i]); // 부호는 버림.
			int ii = getPrevI(i);
			cRo[j] = aRo[ii] < 0 ? cRo[j] : -cRo[j]; // 부호 반대.

			cRo[j + N] = cRo[j];
		}

		// 반대방향일 경우 비교, -1 은 같지 않음.
		int kmp = kmpMatcher(cRo, bRo);

		// 같은 방향 경우 비교
		// (1 5 4 3 6 7 1 5 4 3 6 7 -> 3 6 7 1 5 4 : 포함 된다면 같음.) 
		if (kmp == -1) { // aRo를 두번 이어 붙여서 cRo를 만들어 비교.
			System.arraycopy(aRo, 0, cRo, 0, N);
			System.arraycopy(aRo, 0, cRo, N, N);
			kmp = kmpMatcher(cRo, bRo);
		}

		int result = kmp == -1 ? 0 : 1;
		return result;
	}

	static int getPrevI(int i) {
		return i == 0 ? N - 1 : i - 1;
	}

	public static int[] prefixFunction(int[] s) {
		int[] p = new int[s.length];
		int k = 0;
		for (int i = 1; i < s.length; i++) {
			while (k > 0 && s[k] != s[i])
				k = p[k - 1];
			if (s[k] == s[i])
				++k;
			p[i] = k;
		}
		return p;
	}

	public static int kmpMatcher(int[] s, int[] pattern) {
		int m = pattern.length;
		if (m == 0)
			return 0;
		int[] p = prefixFunction(pattern);
		for (int i = 0, k = 0; i < s.length; i++)
			for (;; k = p[k - 1]) {
				if (pattern[k] == s[i]) {
					if (++k == m)
						return i + 1 - m;
					break;
				}
				if (k == 0)
					break;
			}
		return -1;
	}

```
https://github.com/congr/world/tree/master/201606/02_Problem

**Comment by congr** [comment]
훌륭한 파이썬

```
# 두 경로가 같은지 검사
# 같으면 1, 다르면 0을 반환한다.
def isSame(p1, p2):
    s1 = "".join(p1) * 2
    s2 = "".join(p2)
    return 1 if (s2 in s1) else 0
 
# 역방향 경로 구하기
def reverse(path):
    return reversed([copySignReverse(x, y) for x, y in zip(path[1:] + path[:1], path)])
 
# x의 절대값은 유지하면서 y의 부호만 반대로 적용
# x가 2일 때 y가 -1이면 결과는 2이고, y가 1이면 결과는 -2가 된다. x가 -2일 때에도 y의 부호에 따라 결정된다.
def copySignReverse(x, y):
    if x[0] == '-':
        x = x[1:]
    if y[0] == '-':
        return x
    else:
        return '-' + x
    # return '-'*(y[0] != '-') + x[x[0] == '-':]와 같이 쓸 수도 있다.
 
# 여기부터 시작
T = input()
for t in range(T):
    N = input()
    path1 = raw_input().split()
    path2 = raw_input().split()
    result = isSame(path1, path2) | isSame(path1, reverse(path2))
    print result
```

**Comment by congr** [comment]
코드잼 당시 이 문제를 푼 게 더 대단하네. 다시 풀어보는데 더 헤맨거 같다.
KMP를 안쓰니 오래 걸린다. 에어에서 거의 안돌아가네..
```
            int[] A = new int[N];
            int[] B = new int[N];
            for (int i = 0; i < N; i++) A[i] = sc.nextInt();
            for (int i = 0; i < N; i++) B[i] = sc.nextInt();
            
            int[] BB = concatArray(B, B);
            int[] R = new int[N];
            
            // A -> R reverse
            // -2, 3, 2, -2, -3, -4, -7, -5 를 뒤집으면
            // 5, 7, 4, 3, -2, -2, 3, 2 이렇게 되야함
            for (int i = 0, j = N - 1; i < N; i++, j--) {
                int k = j - 1;
                if (k < 0) k = N - 1;
                R[i] = Math.abs(A[j]); // 부호 버리고 역순
                R[i] = A[k] < 0 ? R[i] : -R[i]; // 부호 바로 한칸 앞것의 반대
            }
            
            String BBstr = toStringfromIntArray(BB);
            String Astr = toStringfromIntArray(A); // original A
            String Rstr = toStringfromIntArray(R); // reverse A
            
            int isSame = 0;
            if (BBstr.indexOf(Astr) >= 0) isSame = 1;
            if (BBstr.indexOf(Rstr) >= 0) isSame = 1;
            
            int result = isSame;
```

**Comment by congr** [comment]
숫자는 역순으로 하되, 부호는 바로 이전 인덱스의 반대 부호를 붙인다.
왜냐하면 숫자의 부호는 다음 방향을 지시하는 것으로 반대방향으로 진행할 경우 해당 숫자 부호가 아닌 바로 앞 부호를 가져와야 된다.
![image](https://user-images.githubusercontent.com/9853714/30489139-65a5d926-9a71-11e7-8083-7d9656796a07.png)

**Comment by chaelotus** [comment]
안녕하세요! 제가 지금 학교 과제중에 똑같은 문제를 풀고 있습니다.! 
그래서 참고하여 저는 c언어로 코딩했는데
학교에서 제공한 입출력 샘플데이터로 출력결과를 확인한 결과 답이 안맞는 경우도 있어서요! 
근데 직각다각형 정보를 가르쳐주는 N을 예를 들어 268개 이렇게 된 경우에  답이 틀려 디버깅할 엄두도 안나네요 ㅠㅠ
위의 문제에 나온 입출력 정보로 하면 출력에 1 0 1 1 0 이렇게 정답이 나오는데 어느 부분이 잘못되었는지
실례가 되지 않는다면 제가 작성한 코드를 봐줄 수 있을까요??ㅠㅠ

**Comment by congr** [comment]
안녕하세요, 질문해줘서 고마워요 사실 문제 자체가 기억이 안나긴 하네요 오래전일이라..

라지셋 하기 전에 모든 경우의 수를 인풋으로 정리해서 돌려보세요. 큰 라지셋은 문자열 비교만 빠르게 하는것에 의미가 있지 로직 자체는
변함이 없어 보이네요.

제가 코드를 봐서 문제를 찾을 수도 있겠지만, 그보단 .. 직접 논리적으로 맞는지 먼저 한번 따져보세요..
그런데 인풋에 0이 있나요? 어떤 값이 0으로 되어 버리는지도 한번 찾아보다 보면 도움이 될 것 같아요.

큰 도움이 못되어 미안하네요, 잘 해결하길 바래요!
안되면 또 연락주세요.
